README.md

Added info about USERNAME in the readme

---

main.py

This code will prevent commits like this: https://github.com/athul/athul/commit/82e4dae404f5cdfc083b4792da8e7441261cda3b

Updated code to do commit only if readme changed

---

README.md
main.py

fix: Added WakaTime info; Some tweaks

---

README.md
main.py

- Added week number:
```python
08. import datetime
...
16. this_week = datetime.datetime.now().strftime('%W')
...
24.     return '```text\n'+'Week #'+this_week+'\n'+data+'\n```'
```
- Applied [`snake_case`](https://en.wikipedia.org/wiki/Snake_case) at some places.
- Double quotes for f-strings. Rest got single quotes. `¯\_(ツ)_/¯`
- Some linting fixes and a typo.

feat: Added week #number to dev metrics

---

README.md
action.yml
main.py

Due to Feedback, I guess the week in the Top should be made optional since it could increase the clutter in the readme. This patch is a fix for that. i have to test it a bit and shouldn't be merged till then

Add a Flag for Weeks

---

main.py

Add a try/except block for catching errors

---

main.py

Closes #18
cc: @gautamkrishnar

Add try-except if an empty list occurs and removed the exit function

---

main.py
tests/test_main.py

Now the graph uses `░▒▓█` instead of `░█` only.
The tests are also refactored.

feat: more accurate graph

---

main.py

Added ignore for graphs with 0 hours and 0 minutes

Ignoring zero graph, fixes: #35

---

main.py

Support default branches with names other than master

---

.gitignore
tests/test_main.py

- Import main from absolute if relative path is not available
- Ignored .vscode/ configs

fix: fixes import path

---

tests/test_main.py

Thanks for guiding me !
Created new fork and added my commits. Thanks !

add test_decode_readme, add test_generate_new_readme

---

README.md

This PR updates the path in the issue addressed in#71.

updated readme (closes #71)

---

main.py
poetry.lock
pyproject.toml
tests/test_main.py

- Updates dependencies
- Fix typos
- Refactor nested loop with `itertools.product`
> - [X] Tested. Found it working.
> - [X] Will merge on Saturday (maintainers can review in between).
closes #82

maint: update depens, fix misc typos

---

action.yml
main.py

- Adds hardcoded defaults for envars
- Updates default commit message
- Uses __slots__ for constants
closes: #80

feat: adds show-time flag for unclassified langs

---

CONTRIBUTING.md
Dockerfile
README.md
action.yml
main.py
poetry.lock
pyproject.toml

- Fix issues with retry while fetching API data
- Made readme more reader friendly ;)
- Some improvements in log messages
- Update project dependencies
- [Auto retry with backoff](https://github.com/joe733/waka-readme/blob/30c19dde7482a81d9c4528d9b27723c63b2019fc/main.py#L289-L299) might help address #58 & #85
> _Open to suggestions & improvements_

feat: bumped versions, upd. deps

---

.github/testing.yml
.gitignore
CONTRIBUTING.md
README.md
containerfile
poetry.lock
pyproject.toml

- migrated to python 3.11 & poetry 1.2+
- updated project dependencies & readme
- DockerfileDev is now containerfile
- improve contribution docs
- it includes development with podman

feat: release v0.1.7 🚀

---

main.py

Fixes: https://github.com/athul/waka-readme/issues/106
Working example is in my profile:

Add language_count

---

main.py

fix: adds check to find placeholder in old readme

---

README.md
main.py
pyproject.toml
tests/__init__.py
tests/test_main.py

- revised readme, better theming support, improved wording where needed
- granular config for ruff linter & pyright type checker, re-format code
- update dependencies, bump version

chore: monthly updates for Aug'23; bump version

---

.gitignore
compose.yml
containerfile
pyproject.toml

- fix: 0 discovered tests in container
- uses `containerfile` for testing
- update dependencies, bump version

chore: monthly updates for Sep'23; bump version

---

main.py

fix: `IGNORED_LANGUAGES` is now case-sensitive

---

main.py

fix: `_extract_ignored_languages`

---

main.py

Enhance the `make_title` function to support ISO date formats, improving the robustness of date parsing.
Issue: #173

Improve date parsing in `make_title` function for ISO format
